version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: candidateapi_postgres
    restart: always
    environment:
      POSTGRES_USER: candidateapi
      POSTGRES_PASSWORD: candidate123
      POSTGRES_DB: candidateapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
