# SPRING
spring:
  application:
    name: candidateapi
  datasource:
    url: jdbc:postgresql://localhost:5432/candidateapi_db
    username: candidateapi
    password: candidate123
    driver-class-name: org.postgresql.Driver

# JPA
jpa:
  hibernate:
    ddl-auto: none # FLYWAY CONTROLS SCHEMA
  show-sql: true
  properties:
    hibernate:
      format_sql: true

#FLYWAY
flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration
